# Site settings
title: kiewic (formerly Monkey Weekend)
email: hello@kiewic.com
permalink: /:title
description: This is my personal blog where I post about Windows programming.
baseurl: ""
url: "http://kiewic.com"
github_username: kiewic
twitter:
  username: kiewic
highlighter: rouge
disqusid: 3372890
